#!/bin/sh
# $Id: remap_load,v 1.0 2007/05/26 liuli Exp $
module="ioremap"
device="ioremap"
mode="664"

# Group: since distributions do it differently
if grep -q '^hpcog:' /etc/group; then
    group="hpcog"
else
    group="root"
fi

# invoke insmod with all arguments we got
# and use a pathname, as insmod doesn't look in . by default
/sbin/insmod  ./ioremap.ko   || exit 1

#retrieve major number
major=$(awk "\$2==\"$module\" {print \$1}" /proc/devices)
echo $major
#exit
# Remove stale nodes and replace them, then give gid and perms
# Usually the script is shorter, it's scull that has several devices in it.

rm -f /dev/${device}
mknod  /dev/${device}  c  $major  0
#mknod /dev/${device} c 254 0
#ln -sf ${device} /dev/${device}
chgrp $group /dev/${device} 
chmod $mode  /dev/${device}







